### ISSUE TITLE
npm start报错是为什么

### ISSUE THREAD

**Issue by oyster0118** [angoz/webpack-sample-project#1]
ERROR in ./app/main.js
Module build failed: SyntaxError: C:/Users/oyste/Desktop/webpack-sample-project/app/main.js: Unexpected token (11:8)

>   9 | import './main.css'; // 使用 require 导入 css 文件
> 10 |
> 11 | render( < Greeter / > , document.getElementById('root'));

**Comment by angoz** [comment]
@oyster0118 抱歉，耽误你的时间了。
因提交仓库时少了 [.babelrc](https://github.com/angoz/webpack-sample-project/blob/master/.babelrc) 配置文件。（linux下，以点符号开头的文件自动隐藏了）
